import type { Metadata } from 'next'
import { ChampionsSaveProvider } from '@/components/context/ChampionsSaveProvider';
import './globals.css'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ChampionsSaveProvider>
        <body className="flex w-auto h-screen items-center justify-center bg-slate-900">
          {children}
        </body>
      </ChampionsSaveProvider>
    </html>
  )
}
